
version: '3.4'

volumes:
  pg_data: {}

services:
  db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: another-reader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_HOST: db
    image: just-another-rss-reader:local
    env_file:
      - ./.env
    depends_on:
      - db
    command:
      - app
    ports:
      - "7000:5000"

  collect:
    build:
      dockerfile: Dockerfile
      context: .
    image: just-another-rss-reader:local
    environment:
      DB_HOST: db
    env_file:
      - ./.env
    depends_on:
      - db
      - app 
    command:
      # don't do anything by default, rest is handled by Makefile
      - "invalid"
    ports:
      - "5000:5000"

