
version: '3.4'

volumes:
  pg_data: {}

services:
  db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: another-reader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
