"""Remove feed url

Revision ID: 47141f58bd15
Revises: 4b4ae319d31d
Create Date: 2022-10-02 13:38:03.217725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47141f58bd15'
down_revision = '4b4ae319d31d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'feed_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('feed_url', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
