"""empty message

Revision ID: 47708a3f583c
Revises: dacd4d58bad7
Create Date: 2023-04-16 16:11:35.317932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47708a3f583c'
down_revision = 'dacd4d58bad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_sources', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=True))
    op.add_column('article_sources', sa.Column('categories', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_sources', 'categories')
    op.drop_column('article_sources', 'active')
    # ### end Alembic commands ###
