"""Removing unique

Revision ID: ffbaca69f443
Revises: 47141f58bd15
Create Date: 2022-10-02 15:12:18.068961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbaca69f443'
down_revision = '47141f58bd15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_keywords_keyword_key', 'article_keywords', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('article_keywords_keyword_key', 'article_keywords', ['keyword'])
    # ### end Alembic commands ###
