name: Collect Data from RSS Feeds

on: 
   workflow_dispatch:
   schedule:
     - cron: "5 */4 * * *"

jobs:
  run-collection:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull
        run: |
          docker pull ghcr.io/melhin/ghcr.io/melhin/just-another-rss:main-8cdfb3a
          docker run  --rm --name collector ghcr.io/melhin/ghcr.io/melhin/just-another-rss:main-8cdfb3a: collect
