name: Collect Data from RSS Feeds

on: 
   workflow_dispatch:
   schedule:
     - cron: "5 */4 * * *"

jobs:
  run-collection:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull
        run: |
          docker pull ghcr.io/melhin/ghcr.io/melhin/just-another-rss:main-5f717ca


